### ISSUE TITLE
Can I use database(model) to provide a list of words?

### ISSUE THREAD

**Issue by lilian21** [Askedio/Laravel5-Profanity-Filter#5]
Hello,
   Is there any possibility to provide the list of bad words from database? I need this list to be updated dynamically by the end user. Also I tried to add, as stated in readme, to add profanity.php file in resources/lang/en/ folder but either it doesn't works, either the code inside is wrong.

Thank you,
Lilian

**Comment by gcphost** [comment]
Hi

You can provide an array with the `$badWordsArray` variable, the array can be generated from a database (Model) or anything else.
