### ISSUE TITLE
Error on 5.5

### ISSUE THREAD

**Issue by Epistol** [Askedio/Laravel5-Profanity-Filter#7]
` app\ProfanityFilter.php

     
        protected $replaceWithLength;
     
        protected $config = [];
     
        protected $filteredStrings = [];
     
        protected $wasFiltered = false;
     
        public function __construct($config, $badWordsArray)
        {
            $this->config = $config;
     
            $this->strReplace = $this->config['strReplace'];
     
            $this->reset();
     
            $this->badWords = array_merge(
                $this->config['defaults'],
                $badWordsArray
            );
     
            $this->generateFilterChecks();
        }

      
`

Error : 

`array_merge(): Argument #2 is not an array`

It seems  to have to do with a trans() something that is not interpreted anymore.

**Comment by gcphost** [comment]
Did you publish the config and does it exist? `config/profanity.php`

We've just updated to 5.5 at work and I use my own copy, I'll have to give it a look tomorrow.

**Comment by Epistol** [comment]
Yep : 

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Profanity Filter Configuration
    |--------------------------------------------------------------------------
    |
    |
    */

    /* Disable to replace partial words. */
    'replaceFullWords' => true,

    /* Replace bad words with this, based on length of word */
    'replaceWith' => '*',

    /* Replace related letters */
    'strReplace' => [
            'a' => '(a|a\.|a\-|4|@|Á|á|À|Â|à|Â|â|Ä|ä|Ã|ã|Å|å|α|Δ|Λ|λ)',
            'b' => '(b|b\.|b\-|8|\|3|ß|Β|β)',
            'c' => '(c|c\.|c\-|Ç|ç|¢|€|<|\(|{|©)',
            'd' => '(d|d\.|d\-|&part;|\|\)|Þ|þ|Ð|ð)',
            'e' => '(e|e\.|e\-|3|€|È|è|É|é|Ê|ê|∑)',
            'f' => '(f|f\.|f\-|ƒ)',
            'g' => '(g|g\.|g\-|6|9)',
            'h' => '(h|h\.|h\-|Η)',
            'i' => '(i|i\.|i\-|!|\||\]\[|]|1|∫|Ì|Í|Î|Ï|ì|í|î|ï)',
            'j' => '(j|j\.|j\-)',
            'k' => '(k|k\.|k\-|Κ|κ)',
            'l' => '(l|1\.|l\-|!|\||\]\[|]|£|∫|Ì|Í|Î|Ï)',
            'm' => '(m|m\.|m\-)',
            'n' => '(n|n\.|n\-|η|Ν|Π)',
            'o' => '(o|o\.|o\-|0|Ο|ο|Φ|¤|°|ø)',
            'p' => '(p|p\.|p\-|ρ|Ρ|¶|þ)',
            'q' => '(q|q\.|q\-)',
            'r' => '(r|r\.|r\-|®)',
            's' => '(s|s\.|s\-|5|\$|§)',
            't' => '(t|t\.|t\-|Τ|τ)',
            'u' => '(u|u\.|u\-|υ|µ)',
            'v' => '(v|v\.|v\-|υ|ν)',
            'w' => '(w|w\.|w\-|ω|ψ|Ψ)',
            'x' => '(x|x\.|x\-|Χ|χ)',
            'y' => '(y|y\.|y\-|¥|γ|ÿ|ý|Ÿ|Ý)',
            'z' => '(z|z\.|z\-|Ζ)',
    ],

    /* Replace these words no matter what language. */
    'defaults' => [
        'fuck',
        'shit',
    ],
];
`
The only things that seems strange is that it publish in resources/lang/ and then : 
/vendor/profanity/en / and /es

I'll try to add a folder with my current lang (fr) when i get back in 7h.

**Comment by gcphost** [comment]
Thank you.

I've ran the packages tests on 5.5 and had no issues. I've also verified it at work, both working ok over here.

How are you executing the filter?

Is your config cached?

**Comment by Epistol** [comment]
I was trying to execute it on a DB::table ->insertGetId like so : 

'title' => app('profanityFilter')->filter($request->title);

Error result : 

`\vendor\askedio\laravel5-profanity-filter\app\ProfanityFilter.php

     
        protected $replaceWithLength;
     
        protected $config = [];
     
        protected $filteredStrings = [];
     
        protected $wasFiltered = false;
     
        public function __construct($config, $badWordsArray)
        {
            $this->config = $config;
     
            $this->strReplace = $this->config['strReplace'];
     
            $this->reset();
     
            $this->badWords = array_merge(
                $this->config['defaults'],
                $badWordsArray
            );
     
            $this->generateFilterChecks();
        }
     
        public function reset()
        {
            $this->replaceFullWords($this->config['replaceFullWords']);
     
            $this->replaceWith($this->config['replaceWith']);
     
            return $this;
        }
     
        public function replaceWith($string)
        {
            $this->replaceWith = $string;
     
            $this->replaceWithLength = strlen($this->replaceWith);
     

Arguments

    "array_merge(): Argument #2 is not an array"
`

**Comment by gcphost** [comment]
Hi

I just tested a fresh 5.5 install and had no issues using the example from the readme.

Try editing the `ProfanityFilter.php` file and doing a `dd($badWordsArray);` before `$this->badWords = array_merge`...

**Comment by Epistol** [comment]
It returns me : 

`"Laravel5ProfanityFilter::profanity"
`

**Comment by Epistol** [comment]
So ... ?

**Comment by gcphost** [comment]
Looks to be a version issue, `Laravel5Profanityfilter` was in the first release, the latest does not use that.

Check composer and make sure it's using `1.0.5`

**Comment by gcphost** [comment]
https://github.com/Askedio/Laravel5-Profanity-Filter/blob/8cdb7b4eabd476de6ad066b4cb36dc527c934095/app/Providers/ProfanityFilterServiceProvider.php#L31

vs

https://github.com/Askedio/Laravel5-Profanity-Filter/blob/master/app/Providers/ProfanityFilterServiceProvider.php#L33

**Comment by Epistol** [comment]
Works like a charm after update, thank's !
